export const colorPalette = {
bleu: '#6b8fe0',
gris: '#9aa3ad',
jaune: '#e2c85f',
marron: '#8a5a34',
orange: '#e5791f',
rose: '#d88bb4',
rouge: '#d8675f',
'vert-clair': '#c7e3b5',
'vert-foncé': '#4f8247',
violet: '#9a7edc',
none: '#c7c7c7',
};




export function resolveColor(token) {
return colorPalette[token] ?? colorPalette.none;
}

export function cardStyle(token) {
const resolved = resolveColor(token);
return `--card-color: ${resolved}; --card-light: ${lighten(resolved)};`;
}

export function lighten(hex, amount = 40) {
let r = parseInt(hex.slice(1, 3), 16);
let g = parseInt(hex.slice(3, 5), 16);
let b = parseInt(hex.slice(5, 7), 16);
r = Math.min(255, r + amount);
g = Math.min(255, g + amount);
b = Math.min(255, b + amount);
return `rgb(${r},${g},${b})`;
}


export const NOMBRE_CARTES_COULEURS = {
  'Hêtre': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 1, violet: 0 },
  'Bouleau': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 1, 'vert-foncé': 0, violet: 0 },
  'Sapin Douglas': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Marronnier commun': { bleu: 0, gris: 1, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Tilleul': { bleu: 0, gris: 0, jaune: 1, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chêne': { bleu: 0, gris: 0, jaune: 0, marron: 1, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Sapin blanc': { bleu: 1, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Erable': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 1, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Jeunes pousses d\'arbres': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0, none: 1 },
  'Bouvreuil pivoine': { bleu: 2, gris: 2, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Pinson des arbres': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Geai des chênes': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Autour des palombes': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Pic épeiche': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chouette hulotte': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Morio': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Paon du jour': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Tabac d\'Espagne': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grand Mars changeant': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grande Tortue': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Écureuil roux': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Mûre': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Girolle': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Amanite tue-mouches': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Mousse': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Coulemelle': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Cèpe de Bordeaux': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Fougère arborescente': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Fraise des bois': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Crapaud commun': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Cistude': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Rainette verte': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Salamandre tachetée': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Luciole': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Fourmi rousse': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Hérisson commun': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Taupe': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Lucane': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Xylocope violet': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Moustique': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Barbastelle d’Europe': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Murin de Bechstein': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Oreillard roux': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grand rhinolophe': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Daim': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Cerf élaphe': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chevreuil vert-foncé': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chevreuil vert-clair': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chevreuil orange': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chevreuil jaune': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chevreuil bleu': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Marcassin': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Sanglier': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Fouine': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Ours brun': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Blaireau européen': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Loir gris': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Lièvre d’Europe': { bleu: 1, gris: 3, jaune: 1, marron: 0, orange: 0, rose: 0, rouge: 1, 'vert-clair': 1, 'vert-foncé': 0, violet: 0, none: 0 },
  'Lynx': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Raton laveur': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Renard roux': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Loup': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Mélèze d’Europe': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Pin cembro': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Marmotte des Alpes': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chamois': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chamois rose': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chamois violet': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chamois gris': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grand tétras': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Lièvre variable': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Bouquetin des Alpes': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Vespère de Savi': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Petit apollon': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Trompette de la mort': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Edelweiss': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Myrtille': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Triton alpestre': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Aigle royal': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Gypaète barbu': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Gentiane': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grand corbeau': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Pipistrelle de Dürer': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Tarier des Près': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Bouleau pubescent': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Noisetier commun': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Prunellier': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Sureau noir': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Pie bavarde': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Rossignol philomèle': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Effraie des clochers': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Carte géographique': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Digitale pourpre': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grande ortie': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grande sauterelle verte': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Abeille mellifère (essaim)': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Tipule': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Pipistrelle commune': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Laie': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Bison d\'Europe': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Campagnol terrestre': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chat forestier': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Putois d\'Europe': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Élan': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Troll': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grotte': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grotte aux chauves-souris': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grotte du collectionneur': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grotte à provisions': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grotte abandonnée': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Grotte de la contrebandière': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Bouleau des tourbières': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Chêne chevelu': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Sapin de Noël': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Palmier': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Panda roux': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Rouge-gorge': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Cigogne blanche': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Cardinal rouge': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Luciole de Say': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Genette': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Coucou': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Renard polaire': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Tulipe des bois': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Citron (papillon)': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Gui': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Campagnol amphibie': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Tulipe sauvage': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Comaret des marais': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
  'Zibeline': { bleu: 0, gris: 0, jaune: 0, marron: 0, orange: 0, rose: 0, rouge: 0, 'vert-clair': 0, 'vert-foncé': 0, violet: 0 },
};

